export const projectList = [
  {
    id: 0,
    title: "The Dojo",
    subheading: "A Project Management System",
    link: "https://github.com/brijrajparmar27/TheDojo---A-Project-Manager",
    primaryImg: "/Project/thedojo.jpg",
    secondaryImg: "/Project/thedojo1.jpg",
    dark: false,
  },
  {
    id: 1,
    title: "ChatRoom",
    subheading: "Community of Like-Minded People",
    link: "https://github.com/brijrajparmar27/Chatroom-V3",
    primaryImg: "/Project/chatroom.jpg",
    secondaryImg: "/Project/chatroom1.jpg",
    dark: false,
  },
  {
    id: 2,
    title: "LinkVault",
    subheading: "Save Links with Ease",
    link: "https://github.com/brijrajparmar27/LinkVault-frontend",
    primaryImg: "/Project/linkvault.jpg",
    secondaryImg: "/Project/linkvault1.jpg",
    dark: true,
  },
  {
    id: 3,
    title: "Cadre",
    subheading: "Employee Management System",
    link: "https://github.com/brijrajparmar27/Cadre-Frontend",
    primaryImg: "/Project/cadre.jpg",
    secondaryImg: "/Project/cadre1.jpg",
    dark: false,
  },
  {
    id: 4,
    title: "JAVA ChatSocket",
    subheading: "Powerful Command line ChatApp",
    link: "https://github.com/brijrajparmar27/ChatSocket-JAVA",
    primaryImg: "/Project/chatsocket.jpg",
    secondaryImg: "/Project/chatsocket1.jpg",
    dark: true,
  },
];
